name: Run axe Linter

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  axe-linter: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          api_key: ${{ secrets.AXE_LINTER_API_KEY }}
