name: Run axe Accessibility Linter
description: Lints all changed files using the axe DevTools Linter
branding:
  icon: "check-circle"
  color: "blue"
inputs:
  github_token:
    description: Github Token
    required: true
  api_key:
    description: axe Linter API Key
    required: true
  axe_linter_url:
    description: axe Linter URL
    required: false
    default: https://axe-linter.deque.com
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: mikefarah/yq@bc5b54cb1d1f720db16c9f75c5b45384d00e5cbf
    - name: Get changed files
      id: changed_files
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      uses: tj-actions/changed-files@4edd678ac3f81e2dc578756871e4d00c19191daf
      with:
        files: |
          **/*.js
          **/*.jsx
          **/*.tsx
          **/*.html
          **/*.vue
          **/*.md
          **/*.markdown
    - name: Run axe linter
      if: steps.changed_files.outputs.any_changed == 'true'
      run: ${{ github.action_path }}/axe-linter.sh
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        API_KEY: ${{ inputs.api_key }}
        CHANGED_FILES: ${{ steps.changed_files.outputs.all_changed_files }}
        AXE_LINTER_URL: ${{ inputs.axe_linter_url }}
      shell: bash
