name: Run axe Accessibility Linter
description: Lints all changed files using the axe DevTools Linter
branding:
  icon: 'check-circle'
  color: 'blue'
inputs:
  github_token:
    description: Github Token
    required: true
  api_key:
    description: axe Linter API Key
    required: false
  axe_linter_url:
    description: axe Linter URL
    required: false
    default: https://axe-linter.deque.com
runs:
  using: 'node20'
  main: 'dist/index.js'
