#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# this file requires bash to run in github actions (github
# actions use dash as default `sh` command)
# @see https://github.com/typicode/husky/issues/1326
bash "$(dirname -- "$0")/build-changed-files.sh"
npx lint-staged
