name: Run yml validator

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  yml-validator:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .nvmrc
      # This validator doesn't accept globs.
      - run: npx yaml-validator action.yml .github/action-example.yml
