name: Run yml validator

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  yml-validator:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc
      # This validator doesn't accept globs.
      - run: npx yaml-validator action.yml .github/action-example.yml
